<?php
define("SSE_CONNECT",0);
define("SSE_SERVER","");
define("SSE_ORIGIN","http://localhost");
define("SSE_MAX_ROWS",2);
define("SSE_TIMEOUT",30);
define("SSE_LATENCY",10);

// DO NOT EDIT - This file is generated by the Administration panel.
// -----------------
// SSE (server-sent events) allows automatic update of the page content. To disable this set SSE_CONNECT to 0
// -----------------
// SSE_CONNECT: To enable SSE set a value in seconds (recommended 10). This is the delay before the client page re-connect server
// SSE_SERVER: Empty string if not using other server. If using an other server, path of the directory ext (with final /) ex: "http://www.domain.com/app/qti/"
// SSE_ORIGIN: Domain of the script sending the SSE events. ex: "http://localhost" if not using other server, otherwhise "http://www.domain.com"
// SSE_MAX_ROWS: Number of recent topics that can be added in the list of topics. When more topics arrive, the oldest is replaced. Recommended 2, maximum 5.
// SSE_TIMEOUT: Server message duration in seconds (recommended 30).
// SSE_LATENCY: This is the delay in seconds (recommended 10) before starting the sse process and updating the page content.
// About SSE polyfill: For legacy browser that does not support SSE, an auto-refresh is used (120 seconds). Setting SSE_CONNECT to 0 will also disable this auto-resh.
// When SSE is enabled following settings can be defined.
//
// Advanced setup:
// - If memcache and sse are on an other server, see about_ext.txt for configuration parametres.
// - SSE_ORIGIN is used as security control to reject messages coming from other servers. It is possible to enter here several origins (with semicolumn)
//   If the qti_srv_sse.php script (i.e. the server script) is on the same server as application, it must be http://localhost.